### ISSUE TITLE
What are your favorite links for R help?

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/2015-04-17-ucsb#15]
@umihoshijima @tombellkelp @TomCSmith @lstevenson09, what are your favorite links for R help? Add them to the issue and we will compile them in the basic R lesson.

**Comment by mqwilber** [comment]
http://stackoverflow.com/

**Comment by TomCSmith** [comment]
Primarily for plotting and `ggplot2`: The _R Graphics Cookbook_ by **Wynston Chang**, [in an online text format](http://proquest.safaribooksonline.com/book/programming/r/9781449363086)

The basics:
[**Quick R**: http://www.statmethods.net/](http://www.statmethods.net/)

_Mixed Effects Models and Extensions in Ecology with R_, by **Zuur et al.**, sometimes called "the penguin book"; [e-book downloadable through UCSB library](http://link.springer.com/book/10.1007%2F978-0-387-87458-6)

The **Use R!** series is largely available as [e-books downloadable from the UCSB library](http://pegasus.library.ucsb.edu/F/6HHV6867NN63AGSJAR144GASMGLCU5CEPY5CR2K1UBN4IVUYN5-24301?func=find-acc&acc_sequence=010043730); they are generally excellent.  (The link is to a search that should find the whole series)

**Comment by lstevenson09** [comment]
Curses! @TomCSmith took all of mine! 

If we want to recommend books, this "Ecological Models and Data in R" by Ben Bolker is awesome http://ms.mcmaster.ca/~bolker/emdbook/ There's one copy at the UCSB library

**Comment by umihoshijima** [comment]
[GGplot2 google group](https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!forum/ggplot2/topics)

**Comment by umihoshijima** [comment]
Also, unless you're some kind of whiz, this is constantly open while you're using ggplot: [ggplot docs](http://docs.ggplot2.org/0.9.2.1/index.html). It's an incredibly well put-together documentation.
