### ISSUE TITLE
What is our official stance on "<-" vs "="?

### ISSUE THREAD

**Issue by umihoshijima** [mqwilber/2015-04-17-ucsb#17]
I'm personally more of an "=" fan, and I've yet to encounter a case where it's gotten me in trouble. I know that they are not 100% interchangeable, but they are within the scope of this class. I personally think that "=" makes things more legible than <-, and I use it for assignment as it is utilized that way in many other programming languages. 

I'm happy to switch over to <- but I wanted to hear the thoughts on this.

**Comment by TomCSmith** [comment]
I'm no purist nor am I strongly opinionated.  I do think we should be consistent throughout our lessons.  So perhaps we should use whichever is most common in what we have already written and thus requires the fewest edits to achieve consistency.

I can see that if you are moving between programming languages, '=' seems like the obvious choice.

But, I wrote my lessons using <-

**Comment by umihoshijima** [comment]
Yeah I'm happy to switch over to <- for this! I noticed that in the intro R lesson, we've mentioned that R users are sticklers for <-... so let's go with that. 

ctrl-f ...

**Comment by TomCSmith** [comment]
I also think that for the most part, R help files and supporting literature use <-, so we may want to be consistent with those documents.

**Comment by mqwilber** [comment]
I find `<-` really annoying and prefer `=`.  It is less keystrokes and more consistent with most other languages (seconding @TomCSmith). However I agree that we should stick with `<-` but definitely mention that you can use `=`.  No problem if you slip back into `=` when teaching though.  I probably accidentally will, lol.
