### ISSUE TITLE
Error in plot(dat)

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/2015-04-17-ucsb#20]
@TomCSmith, I got the following error when i tried `plot(dat)` in the Data/plotting lesson

```
Error in plot.window(...) : need finite 'xlim' values
In addition: Warning messages:
1: In data.matrix(x) : NAs introduced by coercion
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
```

It seems to be because my RStudio can't handle 10 x 10 plot (not sure why). Plotting only the first 9 variables  `plot(dat[, c(1:9)]` works fine for me and everything smaller.  Just FYI if the error pops up for other people tomorrow.

**Comment by TomCSmith** [comment]
@mqwilber (and everyone else).  I had same error, occurred b/c I dat$GenderCorrected defaults to a chr type; I will add a line that converts it to as.factor(), which works
