### ISSUE TITLE
Command line git vs. source tree vs. Rstudio git?

### ISSUE THREAD

**Issue by mqwilber** [mqwilber/2015-04-17-ucsb#7]
Decide whether to teach a git GUI in addition to git command line.  After looking over Rstudio git, I really like it, but I think it is a bit too specific for the purpose of the workshop.  I think if we focus on command line git (i.e. the concepts of git), discuss source tree as  GUI option, and mention that Rstudio git also exists, then learners can decide if they want to pursue Rstudio git after the workshop.  Decision is still in progress...

**Comment by umihoshijima** [comment]
I've been using git for R studio more recently as well, and I have to agree that it's not the best tool. I've been using SourceTree instead and it's pretty rad (though I'm pretty new to git in general). Teaching command line git + opening up sourcetree quickly to show the gui might be a nice way to go.

**Comment by mqwilber** [comment]
Awesome, I agree @umihoshijima .  Let's plan on that for now.

**Comment by TomCSmith** [comment]
Ditto to all of the above.  Though I will probably stick with Sourcetree, command line was a good place to start.

**Comment by mqwilber** [comment]
Sticking with command line git with a brief introduction to SourceTree git at the end of the git lesson
