### ISSUE TITLE
data for ggplot2, reshape2, dplyr

### ISSUE THREAD

**Issue by umihoshijima** [mqwilber/2015-04-17-ucsb#8]
Shall we converge on a dataset to use for these? It would be easier to write the lesson plan around a dataset to motivate the use of these functions.

**Comment by TomCSmith** [comment]
Data files location: should we make a subfolder in "lessons" or a new folder at "2015-04-17-ucsb"?  I have a data file to share once we decide where to have participants get the data for lessons.

**Comment by mqwilber** [comment]
Make a new directory called `data` at "2015-04-17-ucsb" and stick the dataset in there

**Comment by TomCSmith** [comment]
made `data` in "2015-04-17-ucsb".  now contains "Rworkshop_InsectBodySizeData.csv"

**Comment by TomCSmith** [comment]
the `iris` dataset in datasets package is also nice and standard for ggplot; looks like it can be used to illustrate plyr and reshape as well.
